// Copyright (C) 2013-2020 Blockstack PBC, a public benefit corporation
// Copyright (C) 2020 Stacks Open Internet Foundation
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

define_named_enum!(ClarityCostFunction {
    AnalysisTypeAnnotate("cost-analysis-type-annotate"),
    AnalysisTypeCheck("cost-analysis-type-check"),
    AnalysisTypeLookup("cost-analysis-type-lookup"),
    AnalysisVisit("cost-analysis-visit"),
    AnalysisIterableFunc("cost-analysis-iterable-func"),
    AnalysisOptionCons("cost-analysis-option-cons"),
    AnalysisOptionCheck("cost-analysis-option-check"),
    AnalysisBindName("cost-analysis-bind-name"),
    AnalysisListItemsCheck("cost-analysis-list-items-check"),
    AnalysisCheckTupleGet("cost-analysis-check-tuple-get"),
    AnalysisCheckTupleMerge("cost-analysis-check-tuple-merge"),
    AnalysisCheckTupleCons("cost-analysis-check-tuple-cons"),
    AnalysisTupleItemsCheck("cost-analysis-tuple-items-check"),
    AnalysisCheckLet("cost-analysis-check-let"),
    AnalysisLookupFunction("cost-analysis-lookup-function"),
    AnalysisLookupFunctionTypes("cost-analysis-lookup-function-types"),
    AnalysisLookupVariableConst("cost-analysis-lookup-variable-const"),
    AnalysisLookupVariableDepth("cost-analysis-lookup-variable-depth"),
    AstParse("cost-ast-parse"),
    AstCycleDetection("cost-ast-cycle-detection"),
    AnalysisStorage("cost-analysis-storage"),
    AnalysisUseTraitEntry("cost-analysis-use-trait-entry"),
    AnalysisGetFunctionEntry("cost-analysis-get-function-entry"),
    AnalysisFetchContractEntry("cost-analysis-fetch-contract-entry"),
    LookupVariableDepth("cost-lookup-variable-depth"),
    LookupVariableSize("cost-lookup-variable-size"),
    LookupFunction("cost-lookup-function"),
    BindName("cost-bind-name"),
    InnerTypeCheckCost("cost-inner-type-check-cost"),
    UserFunctionApplication("cost-user-function-application"),
    Let("cost-let"),
    If("cost-if"),
    Asserts("cost-asserts"),
    Map("cost-map"),
    Filter("cost-filter"),
    Len("cost-len"),
    ElementAt("cost-element-at"),
    IndexOf("cost-index-of"),
    Fold("cost-fold"),
    ListCons("cost-list-cons"),
    TypeParseStep("cost-type-parse-step"),
    TupleGet("cost-tuple-get"),
    TupleMerge("cost-tuple-merge"),
    TupleCons("cost-tuple-cons"),
    Add("cost-add"),
    Sub("cost-sub"),
    Mul("cost-mul"),
    Div("cost-div"),
    Geq("cost-geq"),
    Leq("cost-leq"),
    Le("cost-le"),
    Ge("cost-ge"),
    IntCast("cost-int-cast"),
    Mod("cost-mod"),
    Pow("cost-pow"),
    Sqrti("cost-sqrti"),
    Log2("cost-log2"),
    Xor("cost-xor"),
    Not("cost-not"),
    Eq("cost-eq"),
    Begin("cost-begin"),
    Hash160("cost-hash160"),
    Sha256("cost-sha256"),
    Sha512("cost-sha512"),
    Sha512t256("cost-sha512t256"),
    Keccak256("cost-keccak256"),
    Secp256k1recover("cost-secp256k1recover"),
    Secp256k1verify("cost-secp256k1verify"),
    Print("cost-print"),
    SomeCons("cost-some-cons"),
    OkCons("cost-ok-cons"),
    ErrCons("cost-err-cons"),
    DefaultTo("cost-default-to"),
    UnwrapRet("cost-unwrap-ret"),
    UnwrapErrOrRet("cost-unwrap-err-or-ret"),
    IsOkay("cost-is-okay"),
    IsNone("cost-is-none"),
    IsErr("cost-is-err"),
    IsSome("cost-is-some"),
    Unwrap("cost-unwrap"),
    UnwrapErr("cost-unwrap-err"),
    TryRet("cost-try-ret"),
    Match("cost-match"),
    Or("cost-or"),
    And("cost-and"),
    Append("cost-append"),
    Concat("cost-concat"),
    AsMaxLen("cost-as-max-len"),
    ContractCall("cost-contract-call"),
    ContractOf("cost-contract-of"),
    PrincipalOf("cost-principal-of"),
    AtBlock("cost-at-block"),
    LoadContract("cost-load-contract"),
    CreateMap("cost-create-map"),
    CreateVar("cost-create-var"),
    CreateNft("cost-create-nft"),
    CreateFt("cost-create-ft"),
    FetchEntry("cost-fetch-entry"),
    SetEntry("cost-set-entry"),
    FetchVar("cost-fetch-var"),
    SetVar("cost-set-var"),
    ContractStorage("cost-contract-storage"),
    BlockInfo("cost-block-info"),
    StxBalance("cost-stx-balance"),
    StxTransfer("cost-stx-transfer"),
    FtMint("cost-ft-mint"),
    FtTransfer("cost-ft-transfer"),
    FtBalance("cost-ft-balance"),
    FtSupply("cost-ft-get-supply"),
    FtBurn("cost-ft-burn"),
    NftMint("cost-nft-mint"),
    NftTransfer("cost-nft-transfer"),
    NftOwner("cost-nft-owner"),
    NftBurn("cost-nft-burn"),
    PoisonMicroblock("poison-microblock"),
});
